In [7]:
import numpy as np

x = np.linspace(0, 10, 5, endpoint=False)
print(x)


[0. 2. 4. 6. 8.]


In [6]:
x = np.linspace(0, 10, 5, endpoint=True)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [8]:
x = np.linspace(0, 10, 5, endpoint=True, dtype=int)
print(x)

[ 0  2  5  7 10]


In [13]:
a = np.random.standard_normal((4))

In [14]:
print(a)

[-0.17739492 -2.29857708  1.68667931 -1.35517827]


In [15]:
sorted_idx = np.argsort(a)
print(sorted_idx)

[1 3 0 2]
